<?php
/**
 * @var $this Tsg_Trial_Block_News
 * @var $collection Tsg_Trial_Model_Resource_News_Collection
 */
?>
<?php
$collection = $this->getCollection();
$this->getPager($collection) ?>
<?php echo $this->getPagerHtml(); ?>
<div>
    <h1><?php echo $this->__('News') ?></h1>
</div>
<?php if ($collection->getSize()): ?>
    <table id="news table">
        <div>
            <?php
            foreach ($collection as $item) { ?>
                <div class="clear-fix">
                    <h3 align="center"><?php echo $item->getTitle(); ?></h3>
                    <p><?php if ($item->getImage()) {
                            echo $this->newsImage($item->getImage());
                        } ?>
                        <span><?php echo $this->newsContent($item->getContent(), $item->getId()); ?></span>
                    </p>
                </div>
            <?php } ?>
        </div>
    </table>
    <script type="text/javascript">decorateTable('news table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('There is no news.'); ?></p>
<?php endif ?>