<?php
$ajaxGetProductsUrl = Mage::getUrl('tsg_review/ajax/getProducts');
$cookieUrl = Mage::getUrl('tsg_review/ajax/deleteCookie');

$skin = Mage::getDesign()->getSkinUrl() . DS . 'js' . DS . 'tsg_review' . DS . 'recenlty_viewed.ejs';
?>
<script type="text/javascript">
    var cookies = document.cookie.indexOf('loggin');
    if(cookies > 0) {
        debugger;
        localStorage.clear();
        deleteLogginCookie('<?php echo $cookieUrl?>');
    }
    var products = getProductsStorage();
    var getProductsUrl = '<?php echo $ajaxGetProductsUrl ?>';
    if (!products) {
        getProductsToLocalStorage(getProductsUrl);
    } else {
        var currentTime = new Date().getTime();
        var createdBlockTime = products['ttl'];
        var difference = currentTime - createdBlockTime;
        var hour = ( difference / (1000 * 60 * 60)).toFixed(1);
        if ( hour >= 1) {
            localStorage.removeItem('productObject');
            getProductsToLocalStorage(getProductsUrl);
        } else {
            renderViewBlock();
        }
    }
</script>