<?php
$ajaxGetProductsUrl = Mage::getUrl('tsg_review/ajax/getProducts');
$cookieUrl = Mage::getUrl('tsg_review/ajax/deleteCookie');
?>
<script type="text/javascript">
    var viewedClass = new recentlyViewed();
    var cookies = document.cookie.indexOf('loggin');
    if(cookies > 0) {
        debugger;
        localStorage.clear();
        viewedClass.deleteLogginCookie('<?php echo $cookieUrl?>');
    }

    var products = viewedClass.getProductsStorage();
    var getProductsUrl = '<?php echo $ajaxGetProductsUrl ?>';
    if (!products) {
        viewedClass.getProductsToLocalStorage(getProductsUrl);
    } else {
        var currentTime = new Date().getTime();
        var createdBlockTime = products['ttl'];
        var difference = currentTime - createdBlockTime;
        var hour = ( difference / (1000 * 60 * 60)).toFixed(1);
        if ( hour >= 1) {
            localStorage.removeItem('productObject');
            viewedClass.getProductsToLocalStorage(getProductsUrl);
        } else {
            viewedClass.renderViewBlock();
        }
    }
</script>